config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root 'post_images#index'
  resources :post_images, only: [:new, :create, :index, :show] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post_image

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :shop_name, presence: true
  validates :image, presence: true
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!,except: [:top]
   before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    post_images_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
 def create
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)  end

  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)  
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    PostComment.find_by(id: params[:id], post_image_id: params[:post_image_id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end
  
   private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end 
    end

  def index
    @post_images = PostImage.page(params[:page]).reverse_order
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end

  private
  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page]).reverse_order
  end
  
  def edit
    @user = User.find(params[:id])
  end 
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>トップページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿フォーム', new_post_image_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>善良な市民同士で無差別に食欲を煽るSNS</p>
            <%= image_tag('logo-white.png') %>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/post_images/_list.html.erb
<div class="card-list-containar py-5">
  <% post_images.each do |post_image| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= link_to post_image_path(post_image.id) do %>
      <%= attachment_image_tag post_image, :image, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= post_image.caption %></p>
          <span><i class="fas fa-user"></i> By <%= post_image.user.name %> ｜ </span>
          <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate post_images %>
</div>

app/views/post_images/index.html.erb
<%= render 'post_images/list', post_images: @post_images %>

app/views/post_images/new.html.erb
<div class="containar">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @post_image.errors.any? %>
          <%= @post_image.errors.count %>件のエラーが発生しました
          <% @post_image.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model: @post_image, local:true do |f| %>
          <%= f.attachment_field :image, class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div class="post-body">
  <%= attachment_image_tag @post_image, :image %>
  <p>ショップ名：<%= @post_image.shop_name %></p>
  <p>説明：<%= @post_image.caption %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日時：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
   <% if @post_image.user == current_user %>
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <% end %>
</div>

<div class="comments">
<p>コメント件数：<%= @post_image.post_comments.count %></p>
<% @post_image.post_comments.each do |post_comment| %>
  <p></p>
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
  <% if post_comment.user == current_user %>
  <div class="comment-delete">
    <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
  </div>
  <% end %>
  <% if @post_image.favorited_by?(current_user) %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
        ♥<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %> いいね
      <% end %>
  <% end %>
    </p>
<% end %>
</div>
<div class="new-comment">
<%= form_with(model:[@post_image, @post_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール画像</h2>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  <%= f.submit "変更を保存" %>
  <% end %>

app/views/users/show.html.erb
<div class="profile-container">
  <h3 class="profile-name"><%= @user.name %></h3>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <% if @user.id == current_user.id %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
</div>
<%= render 'post_images/list', post_images: @post_images %>